# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ap_isuario_yamlcomponentsschemasusuarios import APIsuarioYamlcomponentsschemasusuarios  # noqa: F401,E501
from swagger_server.models.api_contenidoscomponentsschemaspeliculas import APIContenidoscomponentsschemaspeliculas  # noqa: F401,E501
from swagger_server import util


class RecomendacionesPeliculas(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, usuario: APIsuarioYamlcomponentsschemasusuarios=None, recomendaciones: List[APIContenidoscomponentsschemaspeliculas]=None):  # noqa: E501
        """RecomendacionesPeliculas - a model defined in Swagger

        :param id: The id of this RecomendacionesPeliculas.  # noqa: E501
        :type id: str
        :param usuario: The usuario of this RecomendacionesPeliculas.  # noqa: E501
        :type usuario: APIsuarioYamlcomponentsschemasusuarios
        :param recomendaciones: The recomendaciones of this RecomendacionesPeliculas.  # noqa: E501
        :type recomendaciones: List[APIContenidoscomponentsschemaspeliculas]
        """
        self.swagger_types = {
            'id': str,
            'usuario': APIsuarioYamlcomponentsschemasusuarios,
            'recomendaciones': List[APIContenidoscomponentsschemaspeliculas]
        }

        self.attribute_map = {
            'id': 'id',
            'usuario': 'usuario',
            'recomendaciones': 'recomendaciones'
        }
        self._id = id
        self._usuario = usuario
        self._recomendaciones = recomendaciones

    @classmethod
    def from_dict(cls, dikt) -> 'RecomendacionesPeliculas':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The recomendacionesPeliculas of this RecomendacionesPeliculas.  # noqa: E501
        :rtype: RecomendacionesPeliculas
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this RecomendacionesPeliculas.


        :return: The id of this RecomendacionesPeliculas.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this RecomendacionesPeliculas.


        :param id: The id of this RecomendacionesPeliculas.
        :type id: str
        """

        self._id = id

    @property
    def usuario(self) -> APIsuarioYamlcomponentsschemasusuarios:
        """Gets the usuario of this RecomendacionesPeliculas.


        :return: The usuario of this RecomendacionesPeliculas.
        :rtype: APIsuarioYamlcomponentsschemasusuarios
        """
        return self._usuario

    @usuario.setter
    def usuario(self, usuario: APIsuarioYamlcomponentsschemasusuarios):
        """Sets the usuario of this RecomendacionesPeliculas.


        :param usuario: The usuario of this RecomendacionesPeliculas.
        :type usuario: APIsuarioYamlcomponentsschemasusuarios
        """

        self._usuario = usuario

    @property
    def recomendaciones(self) -> List[APIContenidoscomponentsschemaspeliculas]:
        """Gets the recomendaciones of this RecomendacionesPeliculas.


        :return: The recomendaciones of this RecomendacionesPeliculas.
        :rtype: List[APIContenidoscomponentsschemaspeliculas]
        """
        return self._recomendaciones

    @recomendaciones.setter
    def recomendaciones(self, recomendaciones: List[APIContenidoscomponentsschemaspeliculas]):
        """Sets the recomendaciones of this RecomendacionesPeliculas.


        :param recomendaciones: The recomendaciones of this RecomendacionesPeliculas.
        :type recomendaciones: List[APIContenidoscomponentsschemaspeliculas]
        """

        self._recomendaciones = recomendaciones
